### ISSUE TITLE
Remove function-wrapper in middleware

### ISSUE THREAD

**Issue by alexpts** [eightyfive/koa-request-xhr#2]
``` javascript
module.exports = function *(next) {
    this.state.xhr = (this.request.get('X-Requested-With') === 'XMLHttpRequest');
    yield next;
};

...

app.use(xhr);
```

**Comment by alexpts** [comment]
It is break backward compatibility. Up major version after.

**Comment by eightyfive** [comment]
What are the PROs and CONs doing this? I'd like to stick to convention more, I believe the `function` wrapper is the convention (?).

**Comment by alexpts** [comment]
https://github.com/koajs/koa/blob/master/docs/guide.md#writing-middleware

Both versions are correct. I think you are right and return to function better, though more code. This will in the future without damaging the transfer option api
